FROM node:16-alpine

USER root
RUN apk add --update --no-cache python3 make g++ bash

WORKDIR /home/server
COPY server/migrations migrations/
COPY server/*.json server/*.js ./
RUN npm ci

COPY server/src ./src/
COPY server/.env ./.env
RUN npm run build

CMD [ "npm", "run", "start" ]